server:
  port: 8080

mybatis:
  mapper-locations: classpath:mybatis-mappers/*.xml

swagger2:
  title: demo-provider-service
  description: demo服务者项目
  contact-name: cy
  contact-email: 178333@baosight.com
