spring:
  redis:
    host: 122.112.210.156
    port: 6379
    password: 1234qwer
    database: 0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin123
    publisher-returns: true
    publisher-confirms: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    hikari:
      connection-test-query: select 1
logging:
  level:
    com.jcloud.demo.provider.persist.mapper: debug
girl:
  age: 20