server:
  port: 8082
spring:
  application:
    name: simple-provider-user
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    password: root
    username: root
    hikari:
      connection-test-query: select 1
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mybatis-mappers/*.xml
logging:
  level:
    com:
      jcloud:
        framework:
          user:  debug
