server:
  port: 8002
  servlet:
    context-path: /
spring:
  application:
    name: cloud-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpatch:/config