server:
  port: 8002
  servlet:
    context-path: /
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
          git:
          uri:  https://github.com/ksapper/com.jcloud.framework.git
          search-paths: jcloud-config
          timeout: 120
      label: master
eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:8001/eureka
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.cloud.client.ip-address}:${server.port}