server:
  port: 8002
  servlet:
    context-path: /
spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin123
    publisher-returns: true
    publisher-confirms: true
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/ksapper/com.jcloud.framework.git
          search-paths: jcloud-config
          timeout: 60
          basedir: D:\cloud-config-data
      label: master
    stream:
      bindings:
        springCloudBusInput:
          group: config-service
    bus:
      trace:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:8001/eureka
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.cloud.client.ip-address}:${server.port}